export const artists = [
  "MC 張天賦",
  "林靜翬 winifai",
  "Gordon Flanders",
  "Nancy Kwai",
  "馮允謙 Jay Fung",
  "Gareth T",
  "洪嘉豪 Hung Kaho",
  "Faye Wong 王菲",
  "Cloud 雲浩影",
  "林家謙 Terence Lam",
  "Edan 呂爵安",
  "Yan Ting 周殷廷 ",
  "Zpecial",
  "DAY 許軼",
  "moon tang",
  "Kiri T",
  "Marf 邱彥筒",
  "Dear Jane",
  "陳奕迅 Eason Chan",
  "陳蕾 Panther Chan",
];
