export const nameToInstagramMap = {
  "Kiri T": "kiri_thy",
  "moon tang": "moonstyles_",
  "Nancy Kwai": "nancykwai",
  "Cloud 雲浩影": "cloudwann",
  "Gareth T": "gareth_t",
  "Gordon Flanders": "gordon4x",
  "Agnes Kahei": "AGNESCKH",
  "Edan 呂爵安": "edanlui",
  Zpecial: "zpecial_hk",
  "DAY 許軼": "6y_day",
  "MC 張天賦": "mcheung1201",
  "Marf 邱彥筒": "_marifemarife_",
  "Dear Jane": "dearjaneofficial",
  "陳蕾 Panther Chan": "panther_chan",
  "張蔓姿 Gigi": "gigiicheung",
  "Daniel Toh": "daniellltoh",
  "Terry To": "dadudeterry",
  Kwokin: "kwokin_x",
  "Kelly Cheuk": "kellycheuk.jpg",
  "Silas Chow": "silaschow",
  "Chi Chi Li": "chichili",
  Halftalk: "halftalk",
  "Daniel Chu": "thedanielchu",
  "Titus Chan": "titus1118",
  "Adrian Law": "adrian_lhc",
  陳天順: "shunyumo",
  Pizza: "pppizzzaaa",
  "Malik Zain Ali": "malikzainali",
  "李卓軒 Nature Hin": "naturehin_will_not_dm_first",
  "五芳影業 Ng Fong Pictures": "ngfongpictures",
  "Zev Troxler": "zevtroxler",
  "Lee Yat Ding": "leeyatding",
  "Kelly Lui": "kellyluiiii",
  "Deshawn Leung": "dl.518",
  "Jay Tse": "jaytse",
  rosemances: "rosemances",
  "Wilson Chow": "wilson.chowchunkit",
  "Nic Tsui": "nictsui",
  "Larry Wong": "larrywng",
  林若寧: "ningbbbbb",
  Liknifena: "liknifena",
  "Teddy Fan": "teddyfanguitar",
  "Goo Chan": "_goochan_",
  "Justin Yau": "justinyauyan",
  Howai: "wwwwwwwwai",
  "Sze To Pak": "szetopak",
  "Katherine Ho": "katherinehosw",
  "Samuel Wong": "hongjai_makeup",
  "Leo Yuen": "leooo.foto",
  "Tammy Au": "tammyau_makeup",
  "Samson Huang": "SAMSONHUANG",
  LauOnIn: "lauonin",
  "Wing Chan": "wing_chan_",
  "Terron Chan": "tungchantigar",
  "Jason Kwan": "jason_kwan_6878",
  "Ng Long Fung": "nglongfung",
  "Wong Kwok Sing": "singkwokwong",
  "Yeung Sik Yu": "le_maleme",
  "Ho Shun": "hoshun.dariuz",
  "Kaiyo Cheng": "kaiyocheng",
  "Kuen Chung": "welbychung",
  "Bun Shan": "bunbunbunz",
  "So Hei Ping": "soheiyasuda",
  TSC: "tscrew_hk",
  "Ann Ngai": "annngaii",
  "Andrew Tse": "tsebaba",
  "Hubert Tsui": "huberttsui",
  "Chiaki S.": "chiaki_s_",
  "Cliff Chan": "myos_cliffchan",
  "Mo Yu Wan Yee": "anna_money_work",
  "Hailee Chan": "haileyheichan",
  "Paul Kwan": "paulkwanpk",
  "T-Ma": "tma68",
  "Heiward Mak": "heiwardmak",
  "Anjo Leung": "anjoleung",
  SoSoJess: "sosojess",
  BalaPang: "ba__lapang",
  "Wailan So": "soowailan",
  "Moses Cheng": "mosescheng",
  HoYin: "hoyin626",
  Dickson: "yuduck",
  "Donald Fong": "donaldfong",
  "Enoch Cheng": "enoch_cheng",
  "Yan Ng": "yan512",
  "Peter Lam": "peterlammmmm",
  "Jamie Lee": "jamieleehair",
  "Eddy Chu": "___3ddy",
  "Gavin Chan": "gavinchan96_",
  "Isaac Chan": "channel.isaac",
  "Ian Ho": "amph1b_ian",
  "Diana X. Lizhao": "dianalzxy",
  "Yoroko Chan": "yorokochan",
  "Claudia Koh": "claudia.koh",
  $$uperCandy: "super_candy_boy",
  Dena: "dena_chang",
  "Jovany Javier": "jovany_javier_bl",
  "Mike Orange": "mike_orange",
  "Sheng Wong": "shengwong_",
  "June Wan": "junewan",
  "Suey Tang": "suecheung",
  "Felix Leong": "macalerlix",
  Sokin: "sokinghei",
  "Malo Ma": "chuen109",
  Athena: "athena_archive",
  "Connie Chow": "connie_chow_",
  "Adrian Leung": "adrian_leung",
  "Eyilee Chow": "eyileeechow",
  "Nicolas Poon": "icefate_poon",
  CK: "ckw720",
  "Hung 9": "hungsanyiu",
  "Monkee Lee": "monkee.lee",
  "Herman To": "herman_to",
  "Karton Ma": "kartonma",
  "Gloria Tang": "gloriapuiyeetang",
  FMLIK: "fmlik_",
  "Karen Li": "karenlinggg",
  "Wing Tai": "bwingtai",
  "Ava Yau": "avayau",
  "Carmen Lam": "lamcar",
  "Polly Wu": "pwwn",
  "Sarah Yue": "sarahhhyue",
  "Kobi Chan": "kobichan",
  "Cedric Cheung": "cedriccheung_",
  "Joyce Yung": "yungjoyce",
  "Debbie Choi": "debbie_choi_",
  "Taurus Lee": "tauruslee_",
  "Crystal Chan": "crystalc.n.l",
  Sandro: "sandroparis",
  Zara: "zara",
  FuChai: "00.FUCHAI",
  JONO: "itsjonomusic",
  "Sandy Natsuly": "sandynatsuly",
  "Bowie Ong": "bowieong",
  Jihei: "jihei__",
  "Tiffany Lin": "jihei__",
  "Wing Wong": "wingwong_wingwong",
  "Kineks Ho": "ki.neks_ho",
  "Matthew Chan": "itsmatthewchan",
  "Jacky Suen": "jackysuench",
  "David Fok": "_david_fok_",
  Yulam: "yulam.fung",
  "Leo Li": "leoliu_hk",
  Maia: "mariadonnadaza",
  "Matt Chow": "iammattchow",
  "Jonathan Chan": "itsjonomusic",
  musicbyAP: "music_byap",
  marife: "_marifemarife_",
  "Kendra Koh": "kendrakohyr",
  "Hidi Lee": "heidileemakeup",
  "Eric Chan": "ericcyc_",
  "Charson Lam": "charsonlam",
  "Lily Chen": "lilycashchan",
  "Kizz Lau": "kizzlau",
  "Rah Bar & Dessert": "rah_tainan",
  "Ching Chen": "_ching.c",
  "Jocelyn Wang": "jocelyn_wang_music",
  "Susan Hung": "susanhvvss",
  "Avis Or": "avis.or",
  Yiu: "yiuwong",
  "Victor Tse": "tsewai",
  "Samuel Chan": "samuelchxn",
  "Sunny Yip": "sunnyyipsig",
  "Ching Li": "chinglish_and_candarin",
  "Hu Hsuan Wei": "hu_wei_gaffer",
  "Lucas Hsu": "lucas.hsu",
  "Chia Chang Lin": "chia_chang_lin",
  "Li Guan Yan": "stnt_workshop",
  "Shin Yu Sou": "sounds_2026.shinkan",
  "Li Chia Ming": "li.chia.ming",
  "Chi Kai Wang": "wang.chikai",
  "Frak Tang": "tangkaiyiufrank",
  "Jun Hui Lin": "jjfederation_chnfc",
  "Ip Siu": "ipsiu",
  "Tung Wang": "twolayers2",
  "Leon Leung": "leonleung",
  Ocean: "youroceanstyle",
  "Vic Lai": "viccivlai",
  "Marife Yau": "marife_yauna",
  "Sandy Liang": "sandyliang",
  Collusion: "collusionevents",
  Versace: "versace",
  Bode: "bode",
  "Charles & Keith": "charleskeithofficial",
  "Chick Chan": "chickenisachickenz",
  "Sinnie Ng": "_nsyee",
  "Goro Wong": "goroplayground",
  "Tong Hoo Yin": "woohoocreativehk",
  mikeygoincrazy: "mikeygoincrazy",
  DaiShin: "daishin___927",
  Silverstrike: "silverstrike_13",
  "Sp8de K": "sp8dek",
  KKCTO: "kkcto",
  "Quinton Wong": "quinton_wong",
  "Ming Wong": "runn_ming",
  Cage_0512: "cage_0512",
  "Destiny Chan": "destiny.chan",
  "Derek Li": "dereklihair",
  "Deep Choi": "deepakchopra",
  "Eva Chan": "eva.cyl",
  "Yoyo Kwan": "yoyokwans",
  "Manki Cheung": "mankicheung_",
  "Natalie Ting": "natalietong53",
  "Cherie Kong": "cheriedeer",
  "Heisan Hung": "heisanhung",
  "Carmen Ngai": "carcarmenngai",
  "Mavis Lau": "mavis.good.luck",
  "Fai Chan": "dinothedinosaurrrrr",
  "Ariel Au": "arielauzation",
  Jimmy: "jimmyoyang",
  Sai: "saihon",
  Skywalk: "sky._.walkk",
  "Yau Chi Wa": "yauwaiching",
  Sam: "samwill.yau",
  "Fung Ho Ning": "kelvinfungho0519hotmailcom",
  "Li Man Kit": "limankit_lizli",
  Jessica: "krisssica",
  Stone: "lam__tsz_fung",
  JUDE: "judetsang",
  "Ariel Lai": "ariellaimusic",
  "Tsz Yan": "yoo.tszyan",
  Superking: "superking.clo",
  "Gigi Cheung": "gigiicheung",
  "Shadow Yueng": "yuengsha",
  Lupus_C_Hair: "hair_pimple_lupus_psoriasisetc",
  "Cherry Mui": "cherrymuii",
  "Li Hok Fun": "hokfungli",
  "Kaka Chu": "kakachu._",
  "Jana Pang": "jana_pang1111",
  "Jasper Chan": "jasper.ccw",
  "Kwan Yui Hang": "derekkwanyuihang",
  Jess: "krisssica",
  "Anson Chow": "ans0n_chow",
  "Maisy Ho": "maisy_ho",
  "Suetyi Lai": "suetyi_lai",
  "The World Is Your Oyster": "theworld_is_youroyster",
  Maje: "majeparis",
  Pedro: "pedroshoes_official",
  "Avery Wang": "little_circle_circle",
  "Heyman Chan": "heymanchan_",
  "Siu Cheuk Kwan": "simons01044",
  "Natalie Lin": "natalielincomics",
  Linlaomoo: "lin.lao.moo",
  "You Huang Hsiu": "yuhsiang0628",
  "Lin Min-Hua": "minhualin",
  "Min Shiuan Lin": "shiuan1002",
  HALFTALK: "halftalk",
  Yang: "yang_0099",
  "Joshua Chen": "jc_zing",
  "Ou Zhi Jun": "ouzhijun",
  "Chi Chi": "chichili",
  "Mavis Fan": "mavis_fan0227",
  Colin: "colinmakkk",
  halftalk: "halftalk",
  Fortunelens: "fortune.lens.rental",
  "Young Hysan": "younghysan",
  "East City": "eastcity_",
  "The 11th": "the11thgram",
  "Funny Hei": "choilokheifunny",
  "Gary Hui": "garyhui42",
  "Au Yeung": "j__auyeung",
  "Kenny Lee": "kennylee_11",
  "Kim FPV": "kim__fpv",
  "Mike Yeung": "sheepmike",
  "Jimmy Lam": "jimmylam328",
  Kaeja: "kaejaaasb",
  "Ryan Leung": "leungryan",
  Fendi: "fendi",
  MSGM: "msgm",
  Ambush: "ambush_official",
  "Uncle Store": "uncle___store",
  "Constance Chan": "cons_constance",
  "Hin Leung": "chunhinn",
  "Eason Yh Chan": "easooon_",
  "Joshua Evan Lee": "joshevanlee",
  "Matt Sim": "mix_by_matt_sim",
  "Such Slash": "a_splash_of_horse",
  "Erika Chan": "chanerika",
  "Evelyn Chan": "xwy.e",
  "Candy Wong": "candyw1219",
  "Ling Ling": "linglingkwong",
  "Fai Or": "faior.studio",
  "Lai Loi Au": "jason.audrey.laina.louka",
  "Kanis Lai": "kanisnisnis",
  "Such Films": "such.hk",
  "Himberly Chan": "himberly",
  "Evanna Wong": "evawongnava",
  The11th: "the11thgram",
  "Yippy Yip": "bichy0210",
  "Timothy Wong": "timothywong_tim",
  "Nicolas Chan": "laamlaamlaam",
  "Oskar Justesen": "oskarjustesen_",
  "Leanne Mok": "_leannemok",
  "Niki Cheung": "nikiicheung",
  "Ho Siu": "hosiupk",
  "Herman Wan": "hermanhim",
  "Fai Ho": "fai_ho_911",
  "Dun Lamb": "dun_lamb",
  "Kelvin Lam": "kelvinlam_m",
  "Cheuk Chun Wa": "cheuk_chun_wai_simon",
  "Law Chun Kin": "law_chun_kin",
  "Wei Tung Wong": "weitungwong",
  "Man Chi Chu": "mansonvibes",
  "Lo Cheuk Nam": "evannalo1216",
  "Leung Wing Hang": "louis_leung412",
  "Chua Wing Tung": "hattie_chu",
  "Gary Tam": "garytamkh",
  "Heidi Ng": "_serpentundert_",
  Sheep: "sheeper__official",
  Kumi: "kumwtong",
  Lamm: "lamma",
  "Endy Tse": "endytse",
  "Jeff Hui": "jeffhui_ifbbpro",
  "Neo Man": "neoman.rider",
  "Fat Chau": "fatchau828",
  "Terry Kau": "terrykaufman72",
  "Yau Siu": "siuyeeyau",
  Paong: "paopao.ng",
  "Chan Wai Kit": "vc_chanwaikit",
  "Ka Ho": "hungkaho",
  "Keith Wo": "keithwo",
  "Hilary Tsui": "hilaryxtsui",
  "Tifa Tai": "tiffany_wedding",
  "Jeremy Leung": "jeremyleunghair",
  "Sam Law": "xyzlks",
  "Clayton Mang": "claytonmangueira",
  "Gavin So": "gso",
  "Nicholas Cheung": "nicholascheung",
  "Isa Ng": "isabelng523",
  "Warner Music Hong Kong": "warnermusichk",
  "$alty Chick": "saltychick852",
  "Dodo Museum": "dodomuseum",
  "Jade Lam": "jadelamm",
  "Belle Liu": "belle.liuu",
  "Adrian Fan": "adrianfante",
  "Lai Sze": "laiszekuiken",
  "Alice Wan": "alzwong",
  "Sally Leung": "sally.klavier",
  "Roman Kusaiko": "romankusaiko",
  Muteki: "muteki_imports",
  AGA: "agaseen",
  "Wyman Wong": "concertyy",
  "Stephen Ho": "stephenhungofficial",
  "Studio TM": "studiotm.hk",
  "Topaz Leung": "topazy",
  "Jam Yau": "super8jam",
  "Larry Man": "larryman",
  Fung: "ntl.fung",
  Sabrina: "sabrinasa",
  MeatDing: "w_skylett",
  Alice: "huii_alice",
  "Peter Poon": "poon.pete",
  "Cecilia Yiu": "cecilia_yiu",
  "Waner Shen": "waner_jp",
  "Tongyao Guan": "tongyao.guan",
  "Bosho Wong": "bosho_wong",
  "Yingsheng Cai": "yingsheng.cai",
  "Yu Chen": "kanissyu",
  "J Au Yeung": "j__auyeung",
  "Carman Ngai": "carcarmenngai",
  Mok: "mokchunming_",
  "Tam Chi Yin": "tamchiyin0303",
  "Weslyn Ho": "weslyn.n",
  "Tyson Yoshi": "tysonyoshi",
  MadBoii: "_madboii",
  "W.Lin": "mr.glummer",
  "Sean Ling": "seanling_",
  "Theo Yeung": "theo_yeung",
  "Samwill Yau": "samwill.yau",
  "Sunny Liu": "sunny_liu",
  Jo: "joybonesproject",
  "Bobby Wong": "gnoeiioiihw",
  "Poon Reali Am": "poonrealiam",
  "My Concept": "myconcepthk",
  "Jim Tse": "myos_jimtsehair",
  "Carmen C": "car.men.cheng",
  "Milk Chan": "milkchanhair",
  "Matt Li": "mattlimakeup",
  "Vic Kwan": "vic_kwan",
  "Yvonne Yeung": "yeungyvonne",
  "Leung Chin Fung": "chinfungeric",
  "Chan Chun Ming": "dr.alexchan_hk",
  "Wong Chun Kin": "kinchun_20",
  "Chan Hon Tung": "hongchanmaggietung",
  "Lau Wai Kit": "lau.wai.kit",
  "Yun Kwok Wai": "wai.yin.kwok",
  "Ma Hing Chun": "chunhingman",
  "Tam Ching Hoi": "c_catiahoiiiiiii.iii",
  "Cheung Wai Shun": "adshun",
  "Wong Tak Fai": "fai.wongtak",
  "Wong Wai Sum": "wong.w.candy",
  "Thomas Kwok": "thomaskwok1212",
  "Leo Chan": "leochanwm",
  Yanting: "whoisyanting",
  "Cloud Wan": "cloudwann",
  "Neo Yau": "neoyau19",
  "Flora Au": "flora_au413",
  "Ng Hoi Tong": "hoitongkeung",
  "Chan Chun Fung": "chanchunfungmj",
  "Wong Wei Tung": "weitungwong",
  "Alex Fan": "alexfan2047",
  Nam: "nameless_guitars",
  "Harry Chan": "harryhincheuk",
  Yung: "younghysan",
  "9Mui": "vibeeec",
  Sky: "skymusichk",
  "Tony Chan": "tonychan12",
  "Christopher Tang": "chris.topher.t",
  "Ben Lee": "dafengpork",
  "Fok Ho Kwan": "kh.fok",
  Zero: "zero_jai",
  Yin: "yeung_yin",
  Hei: "heisonng",
  "Damon Chan": "cmldamon",
  "Charles Wong": "charles_wghou",
  "Poki Chan": "poki__chan",
  "Jack Wong": "jackwonggg_",
  "Chak Yuen": "hongchak369",
  "Yuen Yat": "yuen.yat_",
  "Edison Mak": "edisonmakhi",
  Gigi: "gigiicheung",
  "Gin Chan": "chan.tsz.ying",
  "Michelle Yuen": "michelleyuenjewelry",
  "Venus Chan": "venuschant",
  "Ziu Yueng": "tyzhao2007",
  "MYCS.Hair": "mycstudio_haircare",
  "Samantha Lai": "samantha.lwh",
  "Lewis Wong": "lewis__ss",
  "Kwok Ho Hin": "kohobro",
  "Pui Yu": "ppui.yee",
  "Sonj Ng": "sonj.ng",
  "Ng Tsz Wai": "tszwai___81",
  "Cheung hing Yueng": "samsonhingcheung",
  "Anson Ng": "prime.anson.ngwh",
  "Alvin Chu": "west_chu",
  "Edwin Tay": "tatt.mr.raccoon",
  Cow10: "cow10_",
  "Edwardo Chan": "edwardochan",
  "Effy Leung": "effy_leunggggg",
  "Jim Chow": "j_pt_trainer",
  "Hero Pun": "hero.punk.oficial",
  "Mia Ling": "mia_lyt",
  Shimeyes: "yordanos_shimeles_",
  ITeSHOP: "iteshop.it",
  "Carmen Cheng": "car.men.cheng",
  "Kidzfrmnowhere.": "kidzfrmnowhere",
  "Terri Li": "terrilllli",
  "Ho Yin Kwok": "hoyin227",
  "Annebell Chan": "annebellchan",
  Tsunboy: "tsunboy",
  "Victor Hong": "victorhong_",
  "Calvin Leung": "calvinleung95",
  "Roy Wong": "hkmasterwan",
  "Ziv Yeung": "myos_zivyeung",
  "Nicko Liu": "myos_nicko",
  Ardnek: "ardneks",
  Seatravel: "seatravelduo",
  "Gabriel De Leon": "gdeleon_music",
  "Hanley Chu": "hanleychu",
  "Rachael Leung": "rachellyt",
  "Mag Lam": "maglam_",
  "Pik Yi": "pikyilee",
  Estelle: "estelleeee1",
  Mandy: "hymannndy",
  "Sum Tik": "sumtik",
  Sparrow: "sparrowdixit.official",
  "Walter Lai": "mud.walter",
  "Tim Chan": "chanloktim",
  "Man Hok": "hok_man_jai",
  "Ting Chun Hei": "_tingbeauty_",
  "Ho Ho Cheung": "by_panghocheung",
  Ibrahimovic: "zlatan",
  "Kelvin Law": "kelvinlaw16",
  "Bigsky Production": "bigsky.production",
  "Joey Young": "youngjoey32",
  "Nic Ko": "nickoletsgo",
  "Lele Cheung": "lelecheung_",
  Eastwindgoodart: "eastwindgoodart",
  "Fanshu.F": "fanshu.f",
  "Sam Leung": "midwin_",
  "To Tsz Kin": "totszkin_",
  "Miko Chan": "gwiyomimiko",
  "Kingjin Cheung": "kingjin.cheung",
  "Emmy Tam": "emmy_tam",
  "Vanko Ng": "vankco",
  "Cavin Lam": "cavin_creations",
  Domz: "domz",
  "Kidd Sun": "kiddsph",
  "Kay Luk": "saaykhlaassikhtrang",
  "Ian Tsoi": "iantsoi_",
  MC: "mcheung1201",
  GooChan: "_goochan_",
  "Problem Child Films": "problemchild_films",
  "Tzuh Suan Chan": "tzuhsuan.chan",
  "Remii Huang": "remiimartinii",
  "Jay Lee": "jayleekwunkit",
  "Li Shu He": "livinginhellnohelp",
  "Hung Jia Jyun": "laukaryung",
  "Min Huang": "wongyiuminganthony",
  "Hsin You Pan": "pan.koubou.shinyou",
  "Sway Wanze": "wanzesway",
  "Chris Ma": "oldvintagemelbourne",
  "Komodo Wu": "bus_wisatakomodo",
  "Jay Fu": "jayfungmusic",
  "Chia Yu Hung": "_yu_hung",
  Cliff: "myos_cliffchan",
  "Sum Sum": "sumsum_dessert",
  "Yu Jr Chi": "amanchu_itami",
  "Wu Cheng Jung": "studiojungle.hk",
  "Lin Chen Wei": "fatlin0617",
  "Chen Da Feng": "minitao__",
  Yee1yee: "yee1yee",
  Ariel: "oreohh",
  "L.h.wu": "l.h.wu",
  "Eddie Weng": "eddie_weng",
  Julie: "julieh75",
  "Ying Te Chen": "hair.style.uk.hk",
  "Cheng Chih Ni": "chickees_ssp",
  "Huang Chen Wei": "adyhcw_818",
  "Zhuang Kai Hao": "kaiii_0415",
  "Lenzbank.": "lenz_bank",
  "Wayne Lin": "waynelin1992",
  "ZBTS Co,Ltd": "btsconstructionswltd",
  "Lin Chia Ying": "t.n.crowns.cheer",
  "CY Chiu": "cyongchiu",
  "Alex Psaroudakis": "alexpsaroudakismastering",
  "The Besties": "bestiesonset",
  "Cody Hui": "codyhui9",
  "Ng Shun Tak": "shuntakng",
  "Leung Chi Wah": "leung_chi_wah_",
  Mo: "moonstyles_",
  "Sam Yau": "_.samyau._",
  "Donald Ng": "donaldglover",
  "Season Chan": "seas_creation",
  "Eric Wong": "ericwong0529",
  "Chili Fong": "zili_chili",
  "Bobo Wong": "bobo.wong.128",
  "Sonia Tam": "soniatcy",
  "John David Dela Peri": "dabeedos",
  "Manmen Tam": "tamaamamamamen",
  "THE BASTARDS": "thebastardsgram",
  Oscar: "oscar_emboaba",
  "Oscar Lee": "oscarlee",
  "Victor Wong": "wvictorwt",
  "Jerry Tai": "jerryckwhk",
  Pan: "pantherchan",
  "Don Mai": "d2on",
  "Jack Lo": "jacklo127_",
  Hirari: "hirari_natsu829",
  "Lamb Cheng": "lambcheng",
  "Percy Shing": "waiyinshing",
  "Phoebe Leung": "phoebelll",
  "York Ngan": "new_york.citi",
  "Miaow Ng": "miaowng__",
  "Suen Mk": "suenmeow",
  "Simon Tso": "tsosimon",
  Y: "yewstwerrrrs",
  "Manie Cheng": "manie.isborn",
  AP: "anson.poon",
  "Kristy Cheng": "kristywailing",
  Jessie: "jessie.jes.sie",
  "Shushu Tong": "shushu__tong",
  "King Yu": "kingyu__",
  Tong: "tong_ming",
  Jennifer: "jenniferyuuu",
  Letty: "letty.leung_",
  Luby: "azalealubyyip",
  Josey: "josephineskylarr",
  Yco: "ycombinator",
  Kitty: "kittyyeungsikyung",
  Owen: "owenpokman",
  King: "kinggnu.jp",
  Gordon: "gordon4x",
  "Rony Kong": "ronykong",
  "Neo Ng": "neo_ng_ig",
  Fanshu: "fanshu.f",
  "Brian Choi": "brianchoi.violin",
  "Bun Chan": "bunchan1221",
  "Kevin Tsang": "kevinkwtsang",
  "Jason Chan": "ckw720",
  "Bryan Loo": "bryan_lsy",
  "Cherie Fung": "cherie.fung",
  "Dorothy Lau": "thedorothylau",
  "Melody Fong": "melody.fong",
  "Tommy Tse": "tommytse_draw",
  Nosylxu: "nosylxu",
  "J Jelly": "jjforjelly",
  "Travis Good": "travisgoood",
  Wenan: "wenan____",
  WanillaCoco: "wanillacoco",
};
