export const nameToInstagramMap = {
  "Kiri T": "kiri_thy",
  "moon tang": "moonstyles_",
  "Nancy Kwai": "nancykwai",
  "Cloud 雲浩影": "cloudwann",
  "Gareth T": "gareth_t",
  "Gordon Flanders": "gordon4x",
  "Edan 呂爵安": "edanlui",
  Zpecial: "zpecial_hk",
  "DAY 許軼": "6y_day",
  "MC 張天賦": "mcheung1201",
  "Marf 邱彥筒": "_marifemarife_",
  "Dear Jane": "dearjaneofficial",
  "陳蕾 Panther Chan": "panther_chan",
  "張蔓姿 Gigi": "gigiicheung",
  "Daniel Toh": "daniellltoh",
  "Terry To": "dadudeterry",
  Kwokin: "kwokin_x",
  "Kelly Cheuk": "kellycheuk.jpg",
  "Silas Chow": "silaschow",
  "Chi Chi Li": "chichili",
  Halftalk: "halftalk",
  "Daniel Chu": "thedanielchu",
  "Titus Chan": "titus1118",
  "Adrian Law": "adrian_lhc",
  陳天順: "shunyumo",
};
