/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LeaderboardRouteImport } from './app/leaderboard'
import { Route as IndexRouteImport } from './app/index'
import { Route as SitemapXmlRouteImport } from './app/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './app/robots.txt'
import { Route as LocationsSlugRouteImport } from './app/locations/$slug'
import { Route as ApiProxyRouteImport } from './app/api/proxy'
import { Route as ApiLocationReverseRouteImport } from './app/api/location/reverse'
import { Route as ApiLocationAddressRouteImport } from './app/api/location/address'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationReverseRoute = ApiLocationReverseRouteImport.update({
  id: '/api/location/reverse',
  path: '/api/location/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationAddressRoute = ApiLocationAddressRouteImport.update({
  id: '/api/location/address',
  path: '/api/location/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/proxy': typeof ApiProxyRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/location/address': typeof ApiLocationAddressRoute
  '/api/location/reverse': typeof ApiLocationReverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/proxy': typeof ApiProxyRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/location/address': typeof ApiLocationAddressRoute
  '/api/location/reverse': typeof ApiLocationReverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/proxy': typeof ApiProxyRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/location/address': typeof ApiLocationAddressRoute
  '/api/location/reverse': typeof ApiLocationReverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/api/proxy'
    | '/locations/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/location/address'
    | '/api/location/reverse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/api/proxy'
    | '/locations/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/location/address'
    | '/api/location/reverse'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/api/proxy'
    | '/locations/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/location/address'
    | '/api/location/reverse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiProxyRoute: typeof ApiProxyRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiLocationAddressRoute: typeof ApiLocationAddressRoute
  ApiLocationReverseRoute: typeof ApiLocationReverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location/reverse': {
      id: '/api/location/reverse'
      path: '/api/location/reverse'
      fullPath: '/api/location/reverse'
      preLoaderRoute: typeof ApiLocationReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location/address': {
      id: '/api/location/address'
      path: '/api/location/address'
      fullPath: '/api/location/address'
      preLoaderRoute: typeof ApiLocationAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiProxyRoute: ApiProxyRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiLocationAddressRoute: ApiLocationAddressRoute,
  ApiLocationReverseRoute: ApiLocationReverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
